version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Adjust the port if necessary
    environment:
      - APP_ENV=production
    restart: always  # Optional: This will ensure the container restarts on failure
    networks:
      - myapp-network  # Optional: Define a custom network for communication between services

networks:
  myapp-network:
    driver: bridge
